use cosmic_settings_config::shortcuts::State as KeyState;
use cosmic_settings_config::shortcuts::{self, Modifiers};
use cosmic_settings_config::shortcuts::action::{Direction, FocusDirection, ResizeDirection, ResizeEdge};
use smithay::input::keyboard::ModifiersState;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Action {
    /// Behaviors managed internally by cosmic-comp.
    Private(PrivateAction),
    /// Behaviors managed via cosmic-settings.
    Shortcut(shortcuts::Action),
}

#[derive(Clone, Debug, Eq, PartialEq)]
// Behaviors which are internally defined and emitted.
pub enum PrivateAction {
    Escape,
    Resizing(
        ResizeDirection,
        ResizeEdge,
        shortcuts::State,
    ),
    /// Toggle the scratchpad (show/hide/cycle). Handler in Phase 3.
    ScratchpadToggle,
    /// Move focused window to scratchpad. Handler in Phase 3.
    ScratchpadMove,
    /// Toggle monocle mode for current workspace. Handler in Phase 4.
    ToggleMonocle,
    /// Dispatch a shell-overlay event by its short name (e.g. `"waypointer_open"`).
    /// Wired to the `shell:` TOML action prefix. Unknown names warn at dispatch.
    ShellEvent(String),
    /// Invoke an action on a user-installed module. Source is the
    /// `module:<module_id>:<action_id>` TOML action prefix — typically
    /// generated by `installd` from a module's `[[keybinding]]`
    /// manifest entry. Forwarded to modules via the event bus.
    ModuleAction {
        module_id: String,
        action_id: String,
    },
    /// Cycle through the configured XKB layouts. `+1` = next,
    /// `-1` = previous. Source: `keyboard_layout_next` /
    /// `keyboard_layout_prev` action strings.
    KeyboardLayoutCycle(i8),
    /// Jump directly to a specific layout by 1-based index. Source:
    /// `keyboard_layout:N`, matching the `workspace_switch:N`
    /// convention.
    KeyboardLayoutSet(u8),
}

/// Map a TOML keybinding action string to an `Action` enum.
///
/// Supports bare action names (`"focus_left"`) and four prefix forms:
/// * `spawn:<command>` — launch an arbitrary shell command
/// * `shell:<event>` — dispatch a shell-overlay event (e.g. `waypointer_open`)
/// * `workspace_switch:<n>` — switch to workspace `n` (1-indexed, 1..=9)
/// * `workspace_move:<n>` — move focused window to workspace `n`
///
/// Returns `None` for unknown action strings or malformed prefix payloads.
pub fn action_from_str(s: &str) -> Option<Action> {
    // Prefix forms are checked first so that a bare match below cannot
    // accidentally swallow e.g. a literal "spawn" without a colon.
    if let Some(cmd) = s.strip_prefix("spawn:") {
        if cmd.is_empty() {
            return None;
        }
        return Some(Action::Shortcut(shortcuts::Action::Spawn(cmd.to_string())));
    }
    if let Some(event) = s.strip_prefix("shell:") {
        if event.is_empty() {
            return None;
        }
        return Some(Action::Private(PrivateAction::ShellEvent(
            event.to_string(),
        )));
    }
    if let Some(n_str) = s.strip_prefix("workspace_switch:") {
        let n: u8 = n_str.parse().ok()?;
        return Some(Action::Shortcut(shortcuts::Action::Workspace(n)));
    }
    if let Some(n_str) = s.strip_prefix("workspace_move:") {
        let n: u8 = n_str.parse().ok()?;
        return Some(Action::Shortcut(shortcuts::Action::MoveToWorkspace(n)));
    }
    if let Some(rest) = s.strip_prefix("module:") {
        // Expect `module_id:action_id`. `splitn(2)` tolerates colons
        // inside action ids (unlikely but cheap to allow).
        let mut parts = rest.splitn(2, ':');
        let module_id = parts.next()?;
        let action_id = parts.next()?;
        if module_id.is_empty() || action_id.is_empty() {
            return None;
        }
        return Some(Action::Private(PrivateAction::ModuleAction {
            module_id: module_id.to_string(),
            action_id: action_id.to_string(),
        }));
    }
    if let Some(n_str) = s.strip_prefix("keyboard_layout:") {
        let n: u8 = n_str.parse().ok()?;
        if n == 0 {
            return None;
        }
        return Some(Action::Private(PrivateAction::KeyboardLayoutSet(n)));
    }

    Some(match s {
        // Tiling
        "toggle_tiling" => Action::Shortcut(shortcuts::Action::ToggleTiling),
        "toggle_window_floating" => Action::Shortcut(shortcuts::Action::ToggleWindowFloating),

        // Focus
        "focus_left" => Action::Shortcut(shortcuts::Action::Focus(FocusDirection::Left)),
        "focus_right" => Action::Shortcut(shortcuts::Action::Focus(FocusDirection::Right)),
        "focus_up" => Action::Shortcut(shortcuts::Action::Focus(FocusDirection::Up)),
        "focus_down" => Action::Shortcut(shortcuts::Action::Focus(FocusDirection::Down)),

        // Move
        "move_left" => Action::Shortcut(shortcuts::Action::Move(Direction::Left)),
        "move_right" => Action::Shortcut(shortcuts::Action::Move(Direction::Right)),
        "move_up" => Action::Shortcut(shortcuts::Action::Move(Direction::Up)),
        "move_down" => Action::Shortcut(shortcuts::Action::Move(Direction::Down)),

        // Resize (handled via PrivateAction::Resizing)
        "resize_shrink_width" => Action::Private(PrivateAction::Resizing(ResizeDirection::Inwards, ResizeEdge::Right, shortcuts::State::Pressed)),
        "resize_grow_width" => Action::Private(PrivateAction::Resizing(ResizeDirection::Outwards, ResizeEdge::Right, shortcuts::State::Pressed)),
        "resize_shrink_height" => Action::Private(PrivateAction::Resizing(ResizeDirection::Inwards, ResizeEdge::Bottom, shortcuts::State::Pressed)),
        "resize_grow_height" => Action::Private(PrivateAction::Resizing(ResizeDirection::Outwards, ResizeEdge::Bottom, shortcuts::State::Pressed)),

        // Fullscreen
        "fullscreen" | "toggle_fullscreen" => Action::Shortcut(shortcuts::Action::Fullscreen),

        // Swap
        "swap_window" => Action::Shortcut(shortcuts::Action::SwapWindow),

        // Workspace
        "workspace_next" => Action::Shortcut(shortcuts::Action::NextWorkspace),
        "workspace_prev" => Action::Shortcut(shortcuts::Action::PreviousWorkspace),

        // Window management
        "close_window" => Action::Shortcut(shortcuts::Action::Close),
        "maximize" | "toggle_maximize" => Action::Shortcut(shortcuts::Action::Maximize),
        "minimize" => Action::Shortcut(shortcuts::Action::Minimize),

        // Lunaris extensions
        "scratchpad_toggle" => Action::Private(PrivateAction::ScratchpadToggle),
        "scratchpad_move" => Action::Private(PrivateAction::ScratchpadMove),
        "toggle_monocle" => Action::Private(PrivateAction::ToggleMonocle),

        // Keyboard layout switching
        "keyboard_layout_next" => Action::Private(PrivateAction::KeyboardLayoutCycle(1)),
        "keyboard_layout_prev" => Action::Private(PrivateAction::KeyboardLayoutCycle(-1)),

        _ => return None,
    })
}

/// Map a key name string to a Keysym for matching.
///
/// Supports single characters ("H", "T"), special names ("Minus", "Space",
/// "Return", "Tab"), and F-keys ("F1"-"F12").
pub fn keysym_from_str(key: &str) -> Option<smithay::input::keyboard::Keysym> {
    use smithay::input::keyboard::Keysym;

    // Single ASCII character.
    if key.len() == 1 {
        let c = key.chars().next().unwrap();
        if c.is_ascii_alphabetic() {
            // XKB keysyms for a-z are 0x61-0x7a.
            return Some(Keysym::new(c.to_ascii_lowercase() as u32));
        }
        if c.is_ascii_digit() {
            // XKB keysyms for 0-9 are 0x30-0x39.
            return Some(Keysym::new(c as u32));
        }
    }

    // Named keys.
    Some(match key.to_lowercase().as_str() {
        "space" => Keysym::space,
        "return" | "enter" => Keysym::Return,
        "tab" => Keysym::Tab,
        "escape" | "esc" => Keysym::Escape,
        "backspace" => Keysym::BackSpace,
        "delete" | "del" => Keysym::Delete,
        "minus" => Keysym::minus,
        "plus" | "equal" => Keysym::equal,
        "bracketleft" => Keysym::bracketleft,
        "bracketright" => Keysym::bracketright,
        "semicolon" => Keysym::semicolon,
        "comma" => Keysym::comma,
        "period" => Keysym::period,
        "slash" => Keysym::slash,
        "backslash" => Keysym::backslash,
        "left" => Keysym::Left,
        "right" => Keysym::Right,
        "up" => Keysym::Up,
        "down" => Keysym::Down,
        "home" => Keysym::Home,
        "end" => Keysym::End,
        "pageup" | "page_up" => Keysym::Page_Up,
        "pagedown" | "page_down" => Keysym::Page_Down,
        "f1" => Keysym::F1,
        "f2" => Keysym::F2,
        "f3" => Keysym::F3,
        "f4" => Keysym::F4,
        "f5" => Keysym::F5,
        "f6" => Keysym::F6,
        "f7" => Keysym::F7,
        "f8" => Keysym::F8,
        "f9" => Keysym::F9,
        "f10" => Keysym::F10,
        "f11" => Keysym::F11,
        "f12" => Keysym::F12,
        _ => return None,
    })
}

/// Convert `cosmic_settings_config::shortcuts::State` to `smithay::backend::input::KeyState`.
pub fn cosmic_keystate_to_smithay(value: KeyState) -> smithay::backend::input::KeyState {
    match value {
        KeyState::Pressed => smithay::backend::input::KeyState::Pressed,
        KeyState::Released => smithay::backend::input::KeyState::Released,
    }
}

/// Convert `smithay::backend::input::KeyState` to `cosmic_settings_config::shortcuts::State`.
pub fn cosmic_keystate_from_smithay(value: smithay::backend::input::KeyState) -> KeyState {
    match value {
        smithay::backend::input::KeyState::Pressed => KeyState::Pressed,
        smithay::backend::input::KeyState::Released => KeyState::Released,
    }
}

/// Compare `cosmic_settings_config::shortcuts::Modifiers` to `smithay::input::keyboard::ModifiersState`.
pub fn cosmic_modifiers_eq_smithay(this: &Modifiers, other: &ModifiersState) -> bool {
    this.ctrl == other.ctrl
        && this.alt == other.alt
        && this.shift == other.shift
        && this.logo == other.logo
}

/// Convert `smithay::input::keyboard::ModifiersState` to `cosmic_settings_config::shortcuts::Modifiers`
pub fn cosmic_modifiers_from_smithay(value: ModifiersState) -> Modifiers {
    Modifiers {
        ctrl: value.ctrl,
        alt: value.alt,
        shift: value.shift,
        logo: value.logo,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_action_from_str_known() {
        assert!(matches!(
            action_from_str("toggle_tiling"),
            Some(Action::Shortcut(shortcuts::Action::ToggleTiling))
        ));
        assert!(matches!(
            action_from_str("focus_left"),
            Some(Action::Shortcut(shortcuts::Action::Focus(FocusDirection::Left)))
        ));
        assert!(matches!(
            action_from_str("scratchpad_toggle"),
            Some(Action::Private(PrivateAction::ScratchpadToggle))
        ));
        assert!(matches!(
            action_from_str("toggle_monocle"),
            Some(Action::Private(PrivateAction::ToggleMonocle))
        ));
    }

    #[test]
    fn test_action_from_str_unknown() {
        assert!(action_from_str("nonexistent").is_none());
        assert!(action_from_str("").is_none());
    }

    #[test]
    fn test_action_from_str_spawn() {
        let a = action_from_str("spawn:foot").unwrap();
        assert!(matches!(a, Action::Shortcut(shortcuts::Action::Spawn(ref s)) if s == "foot"));

        let a = action_from_str("spawn:/usr/bin/firefox --new-window").unwrap();
        assert!(matches!(
            a,
            Action::Shortcut(shortcuts::Action::Spawn(ref s)) if s == "/usr/bin/firefox --new-window"
        ));

        // Empty payload is invalid.
        assert!(action_from_str("spawn:").is_none());
    }

    #[test]
    fn test_action_from_str_shell() {
        let a = action_from_str("shell:waypointer_open").unwrap();
        assert!(matches!(
            a,
            Action::Private(PrivateAction::ShellEvent(ref s)) if s == "waypointer_open"
        ));
        assert!(action_from_str("shell:").is_none());
    }

    #[test]
    fn test_action_from_str_workspace_switch() {
        let a = action_from_str("workspace_switch:3").unwrap();
        assert!(matches!(
            a,
            Action::Shortcut(shortcuts::Action::Workspace(3))
        ));
        assert!(action_from_str("workspace_switch:").is_none());
        assert!(action_from_str("workspace_switch:not_a_number").is_none());
    }

    #[test]
    fn test_action_from_str_workspace_move() {
        let a = action_from_str("workspace_move:5").unwrap();
        assert!(matches!(
            a,
            Action::Shortcut(shortcuts::Action::MoveToWorkspace(5))
        ));
        assert!(action_from_str("workspace_move:").is_none());
    }

    #[test]
    fn test_action_from_str_keyboard_layout() {
        assert!(matches!(
            action_from_str("keyboard_layout_next"),
            Some(Action::Private(PrivateAction::KeyboardLayoutCycle(1)))
        ));
        assert!(matches!(
            action_from_str("keyboard_layout_prev"),
            Some(Action::Private(PrivateAction::KeyboardLayoutCycle(-1)))
        ));
        match action_from_str("keyboard_layout:2").unwrap() {
            Action::Private(PrivateAction::KeyboardLayoutSet(2)) => {}
            other => panic!("expected KeyboardLayoutSet(2), got {other:?}"),
        }
        // 0 is meaningless (1-indexed) — reject so a bad binding is visible.
        assert!(action_from_str("keyboard_layout:0").is_none());
        assert!(action_from_str("keyboard_layout:").is_none());
        assert!(action_from_str("keyboard_layout:abc").is_none());
    }

    #[test]
    fn test_action_from_str_module() {
        match action_from_str("module:com.example.picker:open_picker").unwrap() {
            Action::Private(PrivateAction::ModuleAction {
                module_id,
                action_id,
            }) => {
                assert_eq!(module_id, "com.example.picker");
                assert_eq!(action_id, "open_picker");
            }
            other => panic!("expected ModuleAction, got {other:?}"),
        }
        // Invalid payloads must not parse.
        assert!(action_from_str("module:").is_none());
        assert!(action_from_str("module:only_module_id").is_none());
        assert!(action_from_str("module::action").is_none());
        assert!(action_from_str("module:id:").is_none());
    }

    #[test]
    fn test_keysym_from_str() {
        // Single letters -> lowercase keysym.
        assert!(keysym_from_str("H").is_some());
        assert!(keysym_from_str("T").is_some());
        // Digits.
        assert!(keysym_from_str("1").is_some());
        // Named keys.
        assert!(keysym_from_str("Minus").is_some());
        assert!(keysym_from_str("Space").is_some());
        assert!(keysym_from_str("F1").is_some());
        // Unknown.
        assert!(keysym_from_str("NotAKey").is_none());
    }
}
